# This is the configuration template.
# Please make the file config.yaml in 
# the same directory with the same layout 
# as this and replace the dummy values with 
# the actual corresponding values.

# This is the configuration for the sync tool.
sync:
  bazarr:
    base_url: http://192.168.1.251:6767/ # replace this with your bazarr service url
    api_key: asdai21g3isufykasgfs7iodftas9d8f # replace this with your bazarr API key

  # You can store previous sync times to avoid resyncing the same
  # episodes/movies in future syncs.
  store_previous_sync_times: true # false if you don't want to keep track of previous syncs
  store_previous_sync_times_file_path: ./previous_sync_times.txt # the file path for where to store the previous sync times

  # These are values for controlling maximum API payload sizes.
  # If you are running out of ram, reducing these values may help.
  maximum_movies_to_query_per_request: 10 
  maximum_series_to_query_per_request: 10


# This is the configuration for the tests.
tests:
  bazarr:
    base_url: http://192.168.1.251:6767/ # replace this with your bazarr service url
    api_key: asdai21g3isufykasgfs7iodftas9d8f # replace this with your bazarr API key